#################################
#     Advent of Code Tests      #
#         Year: 2022            #
#           Day: 05             #
#################################
[test.test_01]
part = 1
input = """    [D]
[N] [C]
[Z] [M] [P]
 1   2   3

move 1 from 2 to 1
move 3 from 1 to 3
move 2 from 2 to 1
move 1 from 1 to 2
"""
answer = "CMZ"

[test.test_02]
part = 2
input = """    [D]
[N] [C]
[Z] [M] [P]
 1   2   3

move 1 from 2 to 1
move 3 from 1 to 3
move 2 from 2 to 1
move 1 from 1 to 2
"""
answer = "MCD"
