#################################
#     Advent of Code Tests      #
#         Year: 2022            #
#           Day: 04             #
#################################
[test.test_01]
part = 1
input = """2-4,6-8
2-3,4-5
5-7,7-9
2-8,3-7
6-6,4-6
2-6,4-8
"""
answer = 2

[test.test_02]
part = 2
input = """2-4,6-8
2-3,4-5
5-7,7-9
2-8,3-7
6-6,4-6
2-6,4-8
"""
answer = 4
