#################################
#     Advent of Code Tests      #
#         Year: 2025            #
#           Day: 02             #
#################################
[test.test_01]
part = 1
input = "11-22,95-115,998-1012,1188511880-1188511890,222220-222224,1698522-1698528,446443-446449,38593856-38593862,565653-565659,824824821-824824827,2121212118-2121212124"
answer = 1227775554

[test.test_02]
part = 2
input = "11-22,95-115,998-1012,1188511880-1188511890,222220-222224,1698522-1698528,446443-446449,38593856-38593862,565653-565659,824824821-824824827,2121212118-2121212124"
answer = 4174379265
