#################################
#     Advent of Code Tests      #
#         Year: 2025            #
#           Day: 12             #
#################################
[test.test_01]
part = 1
input = """0:
###
##.
##.

1:
###
##.
.##

2:
.##
###
##.

3:
##.
###
##.

4:
###
#..
###

5:
###
.#.
###

4x4: 0 0 0 0 2 0
12x5: 1 0 1 0 2 2
12x5: 1 0 1 0 3 2"""
answer = 2
