#################################
#     Advent of Code Tests      #
#         Year: 2024            #
#           Day: 10             #
#################################
[test.test_01]
part = 1
input = """0123
1234
8765
9876
"""
answer = 1

[test.test_02]
part = 1
input = """...0...
...1...
...2...
6543456
7.....7
8.....8
9.....9
"""
answer = 2

[test.test_03]
part = 1
input = """..90..9
...1.98
...2..7
6543456
765.987
876....
987....
"""
answer = 4

[test.test_04]
part = 1
input = """10..9..
2...8..
3...7..
4567654
...8..3
...9..2
.....01
"""
answer = 3

[test.test_05]
part = 1
input = """89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
"""
answer = 36

[test.test_06]
part = 2
input = """.....0.
..4321.
..5..2.
..6543.
..7..4.
..8765.
..9....
"""
answer = 3

[test.test_07]
part = 2
input = """..90..9
...1.98
...2..7
6543456
765.987
876....
987....
"""
answer = 13

[test.test_08]
part = 2
input = """012345
123456
234567
345678
4.6789
56789.
"""
answer = 227

[test.test_09]
part = 2
input = """89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
"""
answer = 81
