#################################
#     Advent of Code Tests      #
#         Year: 2025            #
#           Day: 03             #
#################################
[test.test_01]
part = 1
input = """987654321111111
811111111111119
234234234234278
818181911112111"""
answer = 357

[test.test_02]
part = 2
input = """987654321111111
811111111111119
234234234234278
818181911112111"""
answer = 3121910778619
