#################################
#     Advent of Code Tests      #
#         Year: 2025            #
#           Day: 05             #
#################################
[test.test_01]
part = 1
input = """3-5
10-14
16-20
12-18

1
5
8
11
17
32"""
answer = 3

[test.test_02]
part = 2
input = """3-5
10-14
16-20
12-18

1
5
8
11
17
32"""
answer = 14
