#################################
#     Advent of Code Tests      #
#         Year: 2022            #
#           Day: 08             #
#################################
[test.test_01]
part = 1
input = """30373
25512
65332
33549
35390
"""
answer = 21

[test.test_02]
part = 2
input = """30373
25512
65332
33549
35390
"""
answer = 8
