#################################
#     Advent of Code Tests      #
#         Year: 2022            #
#           Day: 12             #
#################################
[test.test_01]
part = 1
input = """Sabqponm
abcryxxl
accszExk
acctuvwj
abdefghi
"""
answer = 31

[test.test_02]
part = 2
input = """Sabqponm
abcryxxl
accszExk
acctuvwj
abdefghi
"""
answer = 29
