#################################
#     Advent of Code Tests      #
#         Year: 2023            #
#           Day: 09             #
#################################
[test.test_01]
part = 1
input = """0 3 6 9 12 15
1 3 6 10 15 21
10 13 16 21 30 45
"""
answer = 114

[test.test_02]
part = 2
input = """0 3 6 9 12 15
1 3 6 10 15 21
10 13 16 21 30 45
"""
answer = 2
