#################################
#     Advent of Code Tests      #
#         Year: 2023            #
#           Day: 11             #
#################################
[test.test_01]
part = 1
args = [2]
input = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
"""
answer = 374

[test.test_02]
part = 2
args = [10]
input = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
"""
answer = 1030

[test.test_03]
part = 2
args = [100]
input = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
"""
answer = 8410

[test.test_04]
part = 2
args = [1_000_000]
input = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
"""
answer = 82000210
