#################################
#     Advent of Code Tests      #
#         Year: 2025            #
#           Day: 09             #
#################################
[test.test_01]
part = 1
input = """7,1
11,1
11,7
9,7
9,5
2,5
2,3
7,3"""
answer = 50

[test.test_02]
part = 2
input = """7,1
11,1
11,7
9,7
9,5
2,5
2,3
7,3"""
answer = 24
