#################################
#     Advent of Code Tests      #
#         Year: 2016            #
#           Day: 13             #
#################################
[test.test_01]
part = 1
input = 10
args = [7, 4]
answer = 11
