#################################
#     Advent of Code Tests      #
#         Year: 2025            #
#           Day: 11             #
#################################
[test.test_01]
part = 1
input = """aaa: you hhh
you: bbb ccc
bbb: ddd eee
ccc: ddd eee fff
ddd: ggg
eee: out
fff: out
ggg: out
hhh: ccc fff iii
iii: out"""
answer = 5

[test.test_02]
part = 2
input = """svr: aaa bbb
aaa: fft
fft: ccc
bbb: tty
tty: ccc
ccc: ddd eee
ddd: hub
hub: fff
eee: dac
dac: fff
fff: ggg hhh
ggg: out
hhh: out"""
answer = 2
