#################################
#     Advent of Code Tests      #
#         Year: 2023            #
#           Day: 24             #
#################################
[test.test_01]
part = 1
args = [7, 27, 7, 27]
input = """19, 13, 30 @ -2,  1, -2
18, 19, 22 @ -1, -1, -2
20, 25, 34 @ -2, -2, -4
12, 31, 28 @ -1, -2, -1
20, 19, 15 @  1, -5, -3
"""
answer = 2

[test.test_02]
part = 2
input = """19, 13, 30 @ -2,  1, -2
18, 19, 22 @ -1, -1, -2
20, 25, 34 @ -2, -2, -4
12, 31, 28 @ -1, -2, -1
20, 19, 15 @  1, -5, -3
"""
answer = 47
