#################################
#     Advent of Code Tests      #
#         Year: 2024            #
#           Day: 18             #
#################################
[test.test_01]
part = 1
input = """5,4
4,2
4,5
3,0
2,1
6,3
2,4
1,5
0,6
3,3
2,6
5,1
1,2
5,5
2,5
6,5
1,4
0,4
6,4
1,1
6,1
1,0
0,5
1,6
2,0
"""
args = [6, 12]  # Sides 6 and wait 12 nanoseconds
answer = 22

[test.test_02]
part = 2
input = """5,4
4,2
4,5
3,0
2,1
6,3
2,4
1,5
0,6
3,3
2,6
5,1
1,2
5,5
2,5
6,5
1,4
0,4
6,4
1,1
6,1
1,0
0,5
1,6
2,0
"""
args = [6, 12]  # Sides 6 and wait 12 nanoseconds
answer = "6,1"
