#################################
#     Advent of Code Tests      #
#         Year: 2024            #
#           Day: 21             #
#################################
[test.test_01]
part = 1
input = """029A
980A
179A
456A
379A"""
answer = 126384
