#################################
#     Advent of Code Tests      #
#         Year: 2022            #
#           Day: 17             #
#################################
[test.test_01]
part = 1
input = ">>><<><>><<<>><>>><<<>>><<<><<<>><>><<>>"
answer = 3068

[test.test_02]
part = 2
input = ">>><<><>><<<>><>>><<<>>><<<><<<>><>><<>>"
answer = 1707
