#################################
#     Advent of Code Tests      #
#         Year: 2023            #
#           Day: 12             #
#################################
[test.test_01]
part = 1
input = """???.### 1,1,3
.??..??...?##. 1,1,3
?#?#?#?#?#?#?#? 1,3,1,6
????.#...#... 4,1,1
????.######..#####. 1,6,5
?###???????? 3,2,1
"""
answer = 21

[test.test_02]
part = 2
input = """???.### 1,1,3
.??..??...?##. 1,1,3
?#?#?#?#?#?#?#? 1,3,1,6
????.#...#... 4,1,1
????.######..#####. 1,6,5
?###???????? 3,2,1
"""
answer = 525152
