#################################
#     Advent of Code Tests      #
#         Year: 2022            #
#           Day: 14             #
#################################
[test.test_01]
part = 1
input = """498,4 -> 498,6 -> 496,6
503,4 -> 502,4 -> 502,9 -> 494,9
"""
answer = 24

[test.test_02]
part = 2
input = """498,4 -> 498,6 -> 496,6
503,4 -> 502,4 -> 502,9 -> 494,9
"""
answer = 93
