#################################
#     Advent of Code Tests      #
#         Year: 2023            #
#           Day: 22             #
#################################
[test.test_01]
part = 1
input = """1,0,1~1,2,1
0,0,2~2,0,2
0,2,3~2,2,3
0,0,4~0,2,4
2,0,5~2,2,5
0,1,6~2,1,6
1,1,8~1,1,9
"""
answer = 5

[test.test_02]
part = 1
input = """0,0,1~0,1,1
1,1,1~1,1,1
0,1,2~1,1,2
0,0,2~0,0,2
"""
answer = 3

[test.test_03]
part = 1
input = """0,0,1~1,0,1
0,1,1~0,1,2
0,0,5~0,0,5
0,0,4~0,1,4
"""
answer = 2

[test.test_04]
part = 2
input = """1,0,1~1,2,1
0,0,2~2,0,2
0,2,3~2,2,3
0,0,4~0,2,4
2,0,5~2,2,5
0,1,6~2,1,6
1,1,8~1,1,9
"""
answer = 7
