#################################
#     Advent of Code Tests      #
#         Year: 2025            #
#           Day: 06             #
#################################
[test.test_01]
part = 1
input = """123 328  51 64
 45 64  387 23
  6 98  215 314
*   +   *   +  """
answer = 4277556

[test.test_02]
part = 2
input = """123 328  51 64
 45 64  387 23
  6 98  215 314
*   +   *   +  """
answer = 3263827
